# Вебинар. Библиотека Pandas

## Проверка связи

**Поставьте в чат:**<br>
\+ если меня видно и слышно<br>
– если нет

**Если у вас нет звука:**

* убедитесь, что на вашем устройстве и в колонках включён звук

* обновите страницу вебинара или закройте страницу и переподключитесь

* откройте вебинар в другом браузере

* перезагрузите ваше устройство и войдите снова

## О спикере

**Погудина Дарья**
- эксперт-разработчик на Python в области информационной безопасности и в финтехе
- сертифицированный специалист по базам данных
- более 8 лет опыта разработки, из них более 4 лет — на Python
- 3 года в сфере информационной безопасности с разработкой ПО на Python

## Правила участия

*   Приготовьте блокнот и ручку, чтобы записывать важные мысли и идеи
*   Продолжительность вебинара — 80 минут
*   Вы можете писать свои вопросы в чат или задавать их вслух
*   Запись вебинара будет доступна в личном кабинете

## Цель занятия

Научиться работать с библиотекой Pandas:
- загружать данные из различных форматов внешних источников (CSV, Excel, HTML, JSON, Parquet)
- фильтровать, сортировать, объединять, группировать и агрегировать данные
- сохранять результат в файл

## План занятия

1. Чтение данных из внешних источников
2. Методы датафреймов
3. Фильтрация данных
4. Сортировка данных
5. Объединение таблиц
6. Группировка и преобразование данных
7. Экспорт данных

## Ваши вопросы

## 1. Чтение данных из внешних источников

### Импорт модуля pandas

In [1]:
import pandas as pd

### Основные методы загрузки данных

| Метод                 | Что делает                                   | На вход                               | На выход           | Частые аргументы                              |
| --------------------- | -------------------------------------------- | ------------------------------------- | ------------------ | --------------------------------------------- |
| `pd.read_clipboard()` | Читает таблицу, скопированную в буфер обмена | —                                     | `DataFrame`        | `sep`                                         |
| `pd.read_html()`      | Извлекает таблицы из HTML                    | путь / HTML / `StringIO`              | список `DataFrame` | `match`, `attrs`                              |
| `pd.read_csv()`       | Читает CSV                                   | путь или URL                          | `DataFrame`        | `sep`, `nrows`, `usecols`, `keep_default_na`  |
| `pd.read_excel()`     | Читает Excel                                 | путь к файлу                          | `DataFrame` / dict | `sheet_name`                                  |
| `pd.read_json()`      | Читает JSON                                  | путь / строка / URL                   | `DataFrame`        | `orient`                                      |
| `pd.json_normalize()` | «Расплющивает» вложенный JSON                | dict / list[dict]                     | `DataFrame`        | `sep`                                         |
| `pd.read_parquet()`   | Читает Parquet                               | путь к файлу                          | `DataFrame`        | —                                             |
| `pd.read_xml()`       | Читает XML                                   | путь или строка                       | `DataFrame`        | `xpath`                                       |
| `pd.read_sql()`       | Выполняет SQL-запрос                         | SQL + connection                      | `DataFrame`        | —                                             |

In [ ]:
# Чтение из буфера обмена
df = pd.read_clipboard(sep=",")
df.head(10)

#### Чтение данных из HTML

In [2]:
tables = pd.read_html("https://en.wikipedia.org/wiki/Minnesota")
print(len(tables))
tables[2].head()

ImportError: `Import lxml` failed.  Use pip or conda to install the lxml package.

In [107]:
import requests
from io import StringIO

url = 'https://en.wikipedia.org/wiki/Minnesota'

header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
}

response = requests.get(url, headers=header)
html_str = StringIO(response.text)
tables = pd.read_html(html_str)

tables[1].head(10)

              Location July (°F) July (°C) January (°F) January (°C)
0          Minneapolis     83/64     28/18         23/7       −4/−13
1           Saint Paul     83/63     28/17         23/6       −5/−14
2            Rochester     82/63     28/17         23/3       −5/−16
3               Duluth     76/55     24/13         19/1       −7/−17
4            St. Cloud     81/58     27/14        18/−1       −7/−18
5              Mankato     86/62     30/16         23/3       −5/−16
6  International Falls     77/52     25/11        15/−6       −9/−21

In [ ]:
# Список таблиц: смотрим каждую
for i, t in enumerate(tables[:3]):
    print(i, t.shape, list(t.columns)[:5])

In [108]:
pd.read_html(html_str, match='United States presidential election results for Minnesota')[0].head()

   Year Republican         Democratic         Third party(ies)
   Year        No.       %        No.       %              No.      %
0  1860      22069  63.53%      11920  34.31%              748  2.15%
1  1864      25055  59.06%      17367  40.94%                0  0.00%
2  1868      43722  60.88%      28096  39.12%                0  0.00%
3  1872      55708  61.27%      35211  38.73%                0  0.00%
4  1876      72955  58.80%      48587  39.16%             2533  2.04%

In [ ]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "html.parser")
tables_bs = soup.find_all("table")

print(f"Найдено таблиц: {len(tables_bs)}")
print(tables_bs[0].prettify()[:500])

In [ ]:
# Одну таблицу из BS отдаём в pandas
first_table_html = str(tables_bs[1])
df = pd.read_html(StringIO(first_table_html))[0]
df.head()

#### Когда использовать `pandas`, а когда `BeautifulSoup`

| Ситуация | Лучше использовать |
|-----------|--------------------|
| Все таблицы со страницы | `pandas.read_html()` |
| Одна таблица по названию / `class` | `match=...` или `attrs={...}` |
| Сложная вёрстка, не только таблицы | `BeautifulSoup` + `pandas` |
| Страница грузится через JS | API / браузерная автоматизация |

#### Импорт данных из файлов

In [2]:
# Чтение из csv-файла
df = pd.read_csv("AAPL.csv", sep=",")
df.head(5)

NameError: name 'pd' is not defined

In [110]:
# Чтение из файла json
df = pd.read_json("sample-stocks-data.json")
df.tail(10)

,company,description,initial_price,price_2002,price_2007,symbol
12,Microsoft,"Microsoft develops, manufactures, licenses, an...",55.72,22.62,29.84,MSFT
13,Monsanto,Monsanto provides agricultural products for fa...,11.47,7.20,86.93,MO
14,PepsiCo,"PepsiCo, Inc. manufactures, markets, and sells...",34.13,36.69,73.74,PEP
15,Starbucks,Starbucks Corp. provides specialty coffee and ...,6.23,10.50,26.84,SBUX
16,Texas Instruments,Texas Instruments designs and sells semiconduc...,53.88,15.58,36.54,TXN
17,Time Warner,Time Warner is a media and entertainment compa...,221.25,36.36,57.18,TWX
18,United Health,UnitedHealth Group provides healthcare service...,7.66,21.85,47.70,UNH
19,Walmart,"Walmart operates retail stores, warehouse club...",56.50,50.51,47.53,WMT
20,Whirlpool,Whirlpool manufactures and sells home applianc...,58.25,46.82,94.29,WHR
21,Xerox,"Xerox Corporation engages in the development, ...",20.87,5.26,17.54,XRX

In [111]:
# Чтение из файла XML
pd.read_xml("stock.xml").head()

  symbol      sector          company  price  change    volume market_cap
0   AAPL  Technology       Apple Inc.  175.5     2.3  45000000       2.8T
1  GOOGL  Technology    Alphabet Inc.  142.8     1.5  28000000       1.8T
2   TSLA  Automotive       Tesla Inc.  245.2    -5.8  65000000       780B
3   MSFT  Technology  Microsoft Corp.  378.9     3.2  32000000       2.9T
4   AMZN  E-commerce  Amazon.com Inc.  155.3     0.8  25000000       1.6T

#### Excel: несколько листов

In [112]:
# По умолчанию читается первый лист
pd.read_excel("report_demo.xlsx").head()

   metric  value
0   users    100
1  errors      3

In [113]:
# Имена всех листов
xl = pd.ExcelFile("report_demo.xlsx")
xl.sheet_names

['Summary', 'Notes', 'Archive']

In [114]:
# Все листы сразу → словарь {имя: DataFrame}
sheets = pd.read_excel("report_demo.xlsx", sheet_name=None)
for name, sdf in sheets.items():
    print(name, sdf.shape)
    print(sdf.head())
    print()

Summary (2, 2)
   metric  value
0   users    100
1  errors      3

Notes (1, 2)
        todo owner
0  clean PII   ops

Archive (2, 2)
            key          value
0  access_token  TOKEN_DEMO_42
1       expires     2023-12-31

#### Parquet

In [115]:
# Чтение parquet
pq = pd.read_parquet("noise_demo.parquet")
pq.head()

   idx  keep  signal
0    0     0     999
1    1     1      72
2    2     0     888
3    3     1     105
4    4     1      33

In [116]:
pq.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   idx     6 non-null      int64
 1   keep    6 non-null      int64
 2   signal  6 non-null      int64
dtypes: int64(3)
memory usage: 276.0 bytes

In [117]:
# Фильтрация и сборка значения из столбца
carrier = pq[pq["keep"] == 1].sort_values("idx")
carrier

   idx  keep  signal
1    1     1      72
3    3     1     105
4    4     1      33

In [118]:
# signal - числовые коды символов
"".join(chr(int(x)) for x in carrier["signal"])

'Hi!'

#### Вложенный JSON: `json_normalize`

In [119]:
import json

raw = json.loads(open("payloads_demo.json", encoding="utf-8").read())
raw

[{'id': 1,
  'payload': {'name': 'a', 'attrs': {'secret_slot': 'DECOY', 'ok': True}}},
 {'id': 2,
  'payload': {'name': 'b',
   'attrs': {'secret_slot': 'REAL_SLOT', 'ok': False}}},
 {'id': 3, 'payload': {'name': 'c', 'attrs': {'note': 'none'}}}]

In [120]:
# Обычный read_json оставляет вложенность внутри ячеек
pd.read_json("payloads_demo.json")

   id                                            payload
0   1  {'name': 'a', 'attrs': {'secret_slot': 'DECOY'...
1   2  {'name': 'b', 'attrs': {'secret_slot': 'REAL_S...
2   3           {'name': 'c', 'attrs': {'note': 'none'}}

In [121]:
# json_normalize раскладывает вложенные поля в столбцы
flat = pd.json_normalize(raw)
flat

,id,payload.name,payload.attrs.secret_slot,payload.attrs.ok,payload.attrs.note
0,1,a,DECOY,True,NaN
1,2,b,REAL_SLOT,False,NaN
2,3,c,NaN,NaN,none

In [122]:
flat.columns

Index(['id', 'payload.name', 'payload.attrs.secret_slot', 'payload.attrs.ok',
       'payload.attrs.note'],
      dtype='str')

#### CSV и значения NA

In [123]:
# По умолчанию N/A, NULL, NaN и т.п. становятся пропусками
pd.read_csv("events_demo.csv")

  event_id audit_token fragment  ord
0       E1          ok      NaN  NaN
1       E2         NaN        A  0.0
2       E3       retry      NaN  NaN
3       E4         NaN        B  1.0
4       E5         NaN        C  2.0
5       E6          ok      NaN  NaN
6       E7         NaN        !  3.0

In [124]:
# keep_default_na=False сохраняет исходные строки
events = pd.read_csv("events_demo.csv", keep_default_na=False)
events

  event_id audit_token fragment ord
0       E1          ok
1       E2         N/A        A   0
2       E3       retry
3       E4        NULL        B   1
4       E5         n/a        C   2
5       E6          ok
6       E7        #N/A        !   3

In [ ]:
na_tokens = {"N/A", "NULL", "n/a", "NaN", "#N/A"}
sub = events[events["audit_token"].isin(na_tokens) & (events["fragment"] != "")]
"".join(sub.sort_values("ord")["fragment"])

#### Параметры чтения: nrows, usecols и другие

In [126]:
df = pd.read_csv("AAPL.csv", sep=',', names=['date','open','high','low','close','adj_close','volume'], header=0)
df.head(10)

         date      open      high       low     close  adj_close     volume
0  1980-12-12  0.513393  0.515625  0.513393  0.513393   0.406782  117258400
1  1980-12-15  0.488839  0.488839  0.486607  0.486607   0.385558   43971200
2  1980-12-16  0.453125  0.453125  0.450893  0.450893   0.357260   26432000
3  1980-12-17  0.462054  0.464286  0.462054  0.462054   0.366103   21610400
4  1980-12-18  0.475446  0.477679  0.475446  0.475446   0.376715   18362400
5  1980-12-19  0.504464  0.506696  0.504464  0.504464   0.399707   12157600
6  1980-12-22  0.529018  0.531250  0.529018  0.529018   0.419162    9340800
7  1980-12-23  0.551339  0.553571  0.551339  0.551339   0.436848   11737600
8  1980-12-24  0.580357  0.582589  0.580357  0.580357   0.459840   12000800
9  1980-12-26  0.633929  0.636161  0.633929  0.633929   0.502287   13893600

In [127]:
# Чтение первых N строк файла
pd.read_csv("AAPL.csv", nrows=5)

         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.513393  0.515625  0.513393  0.513393   0.406782  117258400
1  1980-12-15  0.488839  0.488839  0.486607  0.486607   0.385558   43971200
2  1980-12-16  0.453125  0.453125  0.450893  0.450893   0.357260   26432000
3  1980-12-17  0.462054  0.464286  0.462054  0.462054   0.366103   21610400
4  1980-12-18  0.475446  0.477679  0.475446  0.475446   0.376715   18362400

In [129]:
# Чтение выбранных столбцов
pd.read_csv("AAPL.csv", usecols=["Date", "Close", "Volume"], nrows=100).head()

         Date     Close     Volume
0  1980-12-12  0.513393  117258400
1  1980-12-15  0.486607   43971200
2  1980-12-16  0.450893   26432000
3  1980-12-17  0.462054   21610400
4  1980-12-18  0.475446   18362400

In [128]:
# Чтение файла чанками
for chunk in pd.read_csv("AAPL.csv", chunksize=2000):
    print(chunk.shape)
    print(chunk.head(2))
    break

(2000, 7)
         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.513393  0.515625  0.513393  0.513393   0.406782  117258400
1  1980-12-15  0.488839  0.488839  0.486607  0.486607   0.385558   43971200

In [130]:
?pd.read_csv

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[HashableT, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    date_format: 'str | dict[Hashable, str] | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    low_memory: 'bool' = True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy', 'round_trip'] | None" = None,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
) -> 'DataFrame | TextFileReader'
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Character or regex pattern to treat as the delimiter. ``sep=None`` detects
    the separator from the first valid row of the file with Python's builtin
    sniffer tool, ``csv.Sniffer``; it is supported only by the Python parsing
    engine, which will be used automatically.
    In addition, separators longer than 1 character and different from
    ``'\s+'`` will be interpreted as regular expressions and will also force
    the use of the Python parsing engine. Note that regex delimiters are prone
    to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, optional
    Alias for ``sep``.
header : int, Sequence of int, 'infer' or None, default 'infer'
    Row number(s) containing column labels and marking the start of the
    data (zero-indexed). Default behavior is to infer the column names:
    if no ``names``
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly to ``names`` then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a :class:`~pandas.MultiIndex` on the columns
    e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.

    When inferred from the file contents, headers are kept distinct from
    each other by renaming duplicate names with a numeric suffix of the form
    ``".{count}"`` starting from 1, e.g. ``"foo"`` and ``"foo.1"``.
    Empty headers are named ``"Unnamed: {i}"`` or ``
    "Unnamed: {i}_level_{level}"``
    in the case of MultiIndex columns.
names : Sequence of Hashable, optional
    Sequence of column labels to apply. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
index_col : Hashable, Sequence of Hashable or False, optional
    Column(s) to use as row label(s), denoted either by column labels or column
    indices.  If a sequence of labels or indices is given,
    :class:`~pandas.MultiIndex`
    will be formed for the row labels.

    Note: ``index_col=False`` can be used to force pandas to *not* use the first
    column as the index, e.g., when you have a malformed file with delimiters at
    the end of each line.
usecols : Sequence of Hashable or Callable, optional
    Subset of columns to select, denoted either
    by column labels or column indices.
    If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in ``names`` or
    inferred from the document header row(s).
    If ``names`` are given, the document
    header row(s) are not taken into account. For example, a valid list-like
    ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
    preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
    for columns in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to ``True``. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
dtype : dtype or dict of {Hashable : dtype}, optional
    Data type(s) to apply to either the whole dataset or individual columns.
    E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
    Use ``str`` or ``object`` together with suitable ``na_values`` settings
    to preserve and not interpret ``dtype``.
    If ``converters`` are specified, they will be applied INSTEAD
    of ``dtype`` conversion. Specify a ``defaultdict`` as input where
    the default determines the ``dtype``
    of the columns which are not explicitly
    listed.
engine : {'c', 'python', 'pyarrow'}, optional
    Parser engine to use. The C and pyarrow engines are faster,
    while the python engine
    is currently more feature-complete. Multithreading
    is currently only supported by
    the pyarrow engine. Some features of the "pyarrow" engine
    are unsupported or may not work correctly.
converters : dict of {Hashable : Callable}, optional
    Functions for converting values in specified columns. Keys can either
    be column labels or column indices.
true_values : list, optional
    Values to consider as ``True`` in addition
    to case-insensitive variants of 'True'.
false_values : list, optional
    Values to consider as ``False`` in addition to case-insensitive
    variants of 'False'.
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : int, list of int or Callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (``int``)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning ``True`` if the row should be skipped and ``False``
    otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
    Refers to the number of data rows in the returned DataFrame, excluding:

    * The header row containing column names.
    * Rows before the header row, if ``header=1`` or larger.

    Example usage:

    * To read the first 999,999 (non-header) rows:
      ``read_csv(..., nrows=999999)``

    * To read rows 1,000,000 through 1,999,999:
      ``read_csv(..., skiprows=1000000, nrows=999999)``

na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable},
    optional
    Additional strings to recognize as ``NA``/``NaN``. If ``dict``
    passed, specific
    per-column ``NA`` values.  By default the following values
    are interpreted as
    ``NaN``: empty string, "NaN", "N/A", "NULL", and other common
    representations of missing data.
keep_default_na : bool, default True
    Whether or not to include the default ``NaN`` values when parsing the data.
    Depending on whether ``na_values`` is passed in, the behavior is as follows:

    * If ``keep_default_na`` is ``True``, and ``na_values``
      are specified, ``na_values``
      is appended to the default ``NaN`` values used for parsing.
    * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
      the default ``NaN`` values are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
      the ``NaN`` values specified ``na_values`` are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
      strings will be parsed as ``NaN``.

    Note that if ``na_filter`` is passed in as ``False``,
    the ``keep_default_na`` and
    ``na_values`` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of ``na_values``). In
    data without any ``NA`` values, passing ``na_filter=False`` can improve the
    performance of reading a large file.
skip_blank_lines : bool, default True
    If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
parse_dates : bool, None, list of Hashable, default None
    The behavior is as follows:

    * ``bool``. If ``True`` -> try parsing the index.
    * ``None``. Behaves like ``True`` if ``date_format`` is specified.
    * ``list`` of ``int`` or names.
      e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
      each as a separate date column.

    If a column or index cannot be represented as an array of ``datetime``,
    say because of an unparsable value or a mixture of timezones, the column
    or index will be returned unaltered as an ``object`` data type. For
    non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
    :func:`~pandas.read_csv`.

    Note: A fast-path exists for iso8601-formatted dates.
date_format : str or dict of column -> format, optional
    Format to use for parsing dates and/or times when
    used in conjunction with ``parse_dates``.
    The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
    `strftime documentation
    <https://docs.python.org/3/library/datetime.html
    #strftime-and-strptime-behavior>`_ for more information on choices, though
    note that :const:`"%f"`` will parse all the way up to nanoseconds.
    You can also pass:

    - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
      time string (not necessarily in exactly the same format);
    - "mixed", to infer the format for each element individually. This is risky,
      and you should probably use it along with `dayfirst`.

    .. versionadded:: 2.0.0
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : bool, default True
    If ``True``, use a cache of unique, converted dates to apply the ``datetime``
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

iterator : bool, default False
    Return ``TextFileReader`` object for iteration or getting chunks with
    ``get_chunk()``.
chunksize : int, optional
    Number of lines to read from the file per chunk. Passing a value will cause the
    function to return a ``TextFileReader`` object for iteration.
    See the `IO Tools docs
    <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.

compression : str or dict, default 'infer'
    For on-the-fly decompression of on-disk data.
    If 'infer' and 'filepath_or_buffer' is
    path-like, then detect compression from the following extensions: '.gz',
    '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
    (otherwise no compression).
    If using 'zip' or 'tar', the ZIP file must contain only
    one data file to be read in.
    Set to ``None`` for no decompression.
    Can also be a dict with key ``'method'`` set
    to one of {``'zip'``, ``'gzip'``, ``'bz2'``,
    ``'zstd'``, ``'xz'``, ``'tar'``} and
    other key-value pairs are forwarded to
    ``zipfile.ZipFile``, ``gzip.GzipFile``,
    ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
    ``tarfile.TarFile``, respectively.
    As an example, the following could be passed for
    Zstandard decompression using a
    custom compression dictionary:
    ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

thousands : str (length 1), optional
    Character acting as the thousands separator in numerical values.
decimal : str (length 1), default '.'
    Character to recognize as decimal point (e.g., use ',' for European data).
lineterminator : str (length 1), optional
    Character used to denote a line break. Only valid with C parser.
quotechar : str (length 1), optional
    Character used to denote the start and end of a quoted item. Quoted
    items can include the ``delimiter`` and it will be ignored.
quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL,
    2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
    ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that
    only fields containing special
    characters are quoted (e.g., characters defined
    in ``quotechar``, ``delimiter``,
    or ``lineterminator``.
doublequote : bool, default True
    When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
    whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
    field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    Character used to escape other characters.
comment : str (length 1), optional
    Character indicating that the remainder of line should not be parsed.
    If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter ``header`` but not by
    ``skiprows``. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
    treated as the header.
encoding : str, optional, default 'utf-8'
    Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

encoding_errors : str, optional, default 'strict'
    How encoding errors are treated. `List of possible values
    <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
    ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
    override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
    documentation for more details.
on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
    Specifies what to do upon encountering a bad line (a line with too many fields).
    Allowed values are:

    - ``'error'``, raise an Exception when a bad line is encountered.
    - ``'warn'``, raise a warning when a bad line is
      encountered and skip that line.
    - ``'skip'``, skip bad lines without raising or warning when
      they are encountered.
    - Callable, function that will process a single bad line.
        - With ``engine='python'``, function with signature
          ``(bad_line: list[str]) -> list[str] | None``.
          ``bad_line`` is a list of strings split by the ``sep``.
          If the function returns ``None``, the bad line will be ignored.
          If the function returns a new ``list`` of strings with
          more elements than
          expected, a ``ParserWarning`` will be emitted while
          dropping extra elements.
        - With ``engine='pyarrow'``, function with signature
          as described in pyarrow documentation: `invalid_row_handler
          <https://arrow.apache.org/docs/python
          /generated/pyarrow.csv.ParseOptions.html
          #pyarrow.csv.ParseOptions.invalid_row_handler>`_.

    .. versionchanged:: 2.2.0

        Callable for ``engine='pyarrow'``

low_memory : bool, default True
    Internally process the file in chunks, resulting in lower memory use
    while parsing, but possibly mixed type inference.  To ensure no mixed
    types either set ``False``, or specify the type with the ``dtype`` parameter.
    Note that the entire file is read into a single :class:`~pandas.DataFrame`
    regardless, use the ``chunksize`` or ``iterator``
    parameter to return the data in
    chunks. (Only valid with C parser).
memory_map : bool, default False
    If a filepath is provided for ``filepath_or_buffer``, map the file object
    directly onto memory and access the data directly from there. Using this
    option can improve performance because there is no longer any I/O overhead.
float_precision : {'high', 'legacy', 'round_trip'}, optional
    Specifies which converter the C engine should use for floating-point
    values. The options are ``None`` or ``'high'`` for the ordinary converter,
    ``'legacy'`` for the original lower precision pandas converter, and
    ``'round_trip'`` for the round-trip converter.

storage_options : dict, optional
    Extra options that make sense for a particular storage connection, e.g.
    host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
    are forwarded to ``urllib.request.Request`` as header options. For other
    URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
    forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
    details, and for more examples on storage options refer `here
    <https://pandas.pydata.org/docs/user_guide/io.html?
    highlight=storage_options#reading-writing-remote-files>`_.

dtype_backend : {'numpy_nullable', 'pyarrow'}
    Back-end data type applied to the resultant :class:`DataFrame`
    (still experimental). If not specified, the default behavior
    is to not use nullable data types. If specified, the behavior

#### Чтение данных напрямую из БД с использованием языка SQL

In [131]:
from sqlalchemy import create_engine
engine = create_engine("postgresql+psycopg2://postgres:example@localhost/demo")
df = pd.read_sql("SELECT * FROM timetable", engine)

len(df)
# df.head(10)

21758

## Ваши вопросы

## 2. Методы датафреймов

In [134]:
df = pd.read_csv(
    "AAPL.csv",
    names=["date", "open", "high", "low", "close", "adj_close", "volume"],
    header=0,
)
df.sample()

            date      open      high     low     close  adj_close    volume
2329  1990-03-02  1.196429  1.241071  1.1875  1.205357    0.98065  26224800

In [135]:
# количество строк DF
print(len(df))

9909

In [136]:
df.shape

(9909, 7)

### Простые методы вычисления для нового столбца

In [137]:
df['high_low_diff'] = df['high'] - df['low']

df.head()

,date,open,high,low,close,adj_close,volume,high_low_diff
0,1980-12-12,0.513393,0.515625,0.513393,0.513393,0.406782,117258400,0.002232
1,1980-12-15,0.488839,0.488839,0.486607,0.486607,0.385558,43971200,0.002232
2,1980-12-16,0.453125,0.453125,0.450893,0.450893,0.357260,26432000,0.002232
3,1980-12-17,0.462054,0.464286,0.462054,0.462054,0.366103,21610400,0.002232
4,1980-12-18,0.475446,0.477679,0.475446,0.475446,0.376715,18362400,0.002232

### Получение основных сведений о датафрейме

In [138]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9909 entries, 0 to 9908
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           9909 non-null   str
 1   open           9909 non-null   float64
 2   high           9909 non-null   float64
 3   low            9909 non-null   float64
 4   close          9909 non-null   float64
 5   adj_close      9909 non-null   float64
 6   volume         9909 non-null   int64
 7   high_low_diff  9909 non-null   float64
dtypes: float64(6), int64(1), str(1)
memory usage: 716.2 KB

In [139]:
df.describe()

,open,high,low,close,adj_close,volume,high_low_diff
count,9909.000000,9909.000000,9909.000000,9909.000000,9909.000000,9.909000e+03,9909.000000
mean,32.606849,32.936079,32.277560,32.618030,30.576570,8.582916e+07,0.658519
std,58.415759,59.001576,57.883037,58.471899,56.746275,8.597195e+07,1.422116
min,0.198661,0.198661,0.196429,0.196429,0.155638,3.472000e+05,0.000000
25%,1.071429,1.089286,1.048571,1.071429,0.917643,3.304230e+07,0.035714
50%,1.729286,1.758929,1.696429,1.732143,1.466154,5.766490e+07,0.072857
75%,35.799999,36.265713,35.328571,35.761429,31.042374,1.069992e+08,0.745714
max,324.739990,327.850006,323.350006,327.200012,327.200012,1.855410e+09,26.970016

In [140]:
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume',
       'high_low_diff'],
      dtype='str')

In [141]:
df[['open', 'close']]

            open       close
0       0.513393    0.513393
1       0.488839    0.486607
2       0.453125    0.450893
3       0.462054    0.462054
4       0.475446    0.475446
...          ...         ...
9904  246.520004  258.440002
9905  252.750000  247.740005
9906  250.740005  254.809998
9907  255.600006  254.289993
9908  246.500000  240.910004

[9909 rows x 2 columns]

### Типы данных

In [ ]:
print(df["date"].dtype)
df["date"] = pd.to_datetime(df["date"], format="%Y-%m-%d", errors='coerce')
print(df["date"].dtype)
df.head(3)

str
datetime64[us]

,date,open,high,low,close,adj_close,volume,high_low_diff
0,1980-12-12,0.513393,0.515625,0.513393,0.513393,0.406782,117258400,0.002232
1,1980-12-15,0.488839,0.488839,0.486607,0.486607,0.385558,43971200,0.002232
2,1980-12-16,0.453125,0.453125,0.450893,0.450893,0.357260,26432000,0.002232

### Отдельный столбец: обращение и методы

In [143]:
df['volume'].head()

0    117258400
1     43971200
2     26432000
3     21610400
4     18362400
Name: volume, dtype: int64

In [144]:
df.volume.head()

0    117258400
1     43971200
2     26432000
3     21610400
4     18362400
Name: volume, dtype: int64

In [145]:
type(df['volume'])

pandas.Series

In [146]:
tx = pd.read_csv("bank_transactions.csv")
tx.head()

,account_id,account_type,owner,date,operation_type,amount,description,balance_after
0,ACC001,checking,Иванов И.И.,2025-09-06,deposit,12891.65,Зачисление зарплаты - Сумма: 12891.65 руб.,64486.82
1,ACC001,checking,Иванов И.И.,2025-09-15,deposit,3439.57,Пополнение наличными - Сумма: 3439.57 руб.,125056.31
2,ACC001,checking,Иванов И.И.,2025-09-15,deposit,19010.45,Пополнение наличными - Сумма: 19010.45 руб.,138548.02
3,ACC001,checking,Иванов И.И.,2025-09-28,withdrawal,13516.53,Снятие наличных в банкомате - Сумма: 13516.53 ...,96631.56
4,ACC001,checking,Иванов И.И.,2025-10-02,deposit,16055.06,Зачисление зарплаты - Сумма: 16055.06 руб.,80541.88

In [147]:
# Уникальные значения в столбце
tx.operation_type.unique()

<ArrowStringArray>
['deposit', 'withdrawal', 'interest']
Length: 3, dtype: str

In [148]:
# Количество уникальных значений в столбце
tx.operation_type.nunique()

3

In [149]:
# Распределение количества строк по значениям столбца
tx.operation_type.value_counts()

operation_type
deposit       48
withdrawal    26
interest       6
Name: count, dtype: int64

In [150]:
tx['operation_type'].value_counts(normalize=True)

operation_type
deposit       0.600
withdrawal    0.325
interest      0.075
Name: proportion, dtype: float64

### Категориальные данные

In [151]:
tickets = pd.read_parquet("tickets_demo.parquet")
tickets.head()

  region  n
0     eu  1
1     us  2
2     eu  3
3     ap  4

In [152]:
# dtype category
tickets["region"].dtype

CategoricalDtype(categories=['ap', 'eu', 'us', 'X', 'Y', 'Z'], ordered=False, categories_dtype=str)

In [153]:
# Что встречается в строках
tickets["region"].value_counts()

region
eu    2
ap    1
us    1
X     0
Y     0
Z     0
Name: count, dtype: int64

In [154]:
# Все уровни категории, в том числе неиспользуемые
list(tickets["region"].cat.categories)

['ap', 'eu', 'us', 'X', 'Y', 'Z']

## Ваши вопросы

## 3. Фильтрация данных

In [155]:
mask = tx["amount"] > 10_000
mask.head(10)

0     True
1    False
2     True
3     True
4     True
5     True
6     True
7     True
8    False
9     True
Name: amount, dtype: bool

In [157]:
big = tx[tx["amount"] > 10_000]
big.head()

,account_id,account_type,owner,date,operation_type,amount,description,balance_after
0,ACC001,checking,Иванов И.И.,2025-09-06,deposit,12891.65,Зачисление зарплаты - Сумма: 12891.65 руб.,64486.82
2,ACC001,checking,Иванов И.И.,2025-09-15,deposit,19010.45,Пополнение наличными - Сумма: 19010.45 руб.,138548.02
3,ACC001,checking,Иванов И.И.,2025-09-28,withdrawal,13516.53,Снятие наличных в банкомате - Сумма: 13516.53 ...,96631.56
4,ACC001,checking,Иванов И.И.,2025-10-02,deposit,16055.06,Зачисление зарплаты - Сумма: 16055.06 руб.,80541.88
5,ACC001,checking,Иванов И.И.,2025-10-06,deposit,23357.58,Перевод с другого счета - Сумма: 23357.58 руб.,161905.60

In [158]:
tx[tx["amount"] > 10_000].head()

,account_id,account_type,owner,date,operation_type,amount,description,balance_after
0,ACC001,checking,Иванов И.И.,2025-09-06,deposit,12891.65,Зачисление зарплаты - Сумма: 12891.65 руб.,64486.82
2,ACC001,checking,Иванов И.И.,2025-09-15,deposit,19010.45,Пополнение наличными - Сумма: 19010.45 руб.,138548.02
3,ACC001,checking,Иванов И.И.,2025-09-28,withdrawal,13516.53,Снятие наличных в банкомате - Сумма: 13516.53 ...,96631.56
4,ACC001,checking,Иванов И.И.,2025-10-02,deposit,16055.06,Зачисление зарплаты - Сумма: 16055.06 руб.,80541.88
5,ACC001,checking,Иванов И.И.,2025-10-06,deposit,23357.58,Перевод с другого счета - Сумма: 23357.58 руб.,161905.60

In [159]:
tx[(tx["amount"] > 10_000) & (tx["operation_type"] == "deposit")].head()

,account_id,account_type,owner,date,operation_type,amount,description,balance_after
0,ACC001,checking,Иванов И.И.,2025-09-06,deposit,12891.65,Зачисление зарплаты - Сумма: 12891.65 руб.,64486.82
2,ACC001,checking,Иванов И.И.,2025-09-15,deposit,19010.45,Пополнение наличными - Сумма: 19010.45 руб.,138548.02
4,ACC001,checking,Иванов И.И.,2025-10-02,deposit,16055.06,Зачисление зарплаты - Сумма: 16055.06 руб.,80541.88
5,ACC001,checking,Иванов И.И.,2025-10-06,deposit,23357.58,Перевод с другого счета - Сумма: 23357.58 руб.,161905.60
6,ACC001,checking,Иванов И.И.,2025-10-10,deposit,17831.63,Возврат средств - Сумма: 17831.63 руб.,179737.23

In [160]:
tx[tx["operation_type"].isin(["withdrawal", "deposit"])].head()

,account_id,account_type,owner,date,operation_type,amount,description,balance_after
0,ACC001,checking,Иванов И.И.,2025-09-06,deposit,12891.65,Зачисление зарплаты - Сумма: 12891.65 руб.,64486.82
1,ACC001,checking,Иванов И.И.,2025-09-15,deposit,3439.57,Пополнение наличными - Сумма: 3439.57 руб.,125056.31
2,ACC001,checking,Иванов И.И.,2025-09-15,deposit,19010.45,Пополнение наличными - Сумма: 19010.45 руб.,138548.02
3,ACC001,checking,Иванов И.И.,2025-09-28,withdrawal,13516.53,Снятие наличных в банкомате - Сумма: 13516.53 ...,96631.56
4,ACC001,checking,Иванов И.И.,2025-10-02,deposit,16055.06,Зачисление зарплаты - Сумма: 16055.06 руб.,80541.88

In [161]:
tx[tx["amount"].between(3000, 5000)].head()

,account_id,account_type,owner,date,operation_type,amount,description,balance_after
1,ACC001,checking,Иванов И.И.,2025-09-15,deposit,3439.57,Пополнение наличными - Сумма: 3439.57 руб.,125056.31
22,ACC002,savings,Петров П.П.,2025-10-22,withdrawal,3690.28,Снятие наличных в банкомате - Сумма: 3690.28 руб.,68202.88
31,ACC002,savings,Петров П.П.,2025-12-18,withdrawal,3939.61,Покупка в магазине - Сумма: 3939.61 руб.,63938.88
34,ACC003,checking,Сидорова А.В.,2025-09-16,deposit,4643.33,Возврат средств - Сумма: 4643.33 руб.,35670.82
41,ACC003,checking,Сидорова А.В.,2025-11-23,withdrawal,4627.05,Оплата интернета - Сумма: 4627.05 руб.,64698.48

In [162]:
tx.query('3000 <= amount <= 5000').head()

,account_id,account_type,owner,date,operation_type,amount,description,balance_after
1,ACC001,checking,Иванов И.И.,2025-09-15,deposit,3439.57,Пополнение наличными - Сумма: 3439.57 руб.,125056.31
22,ACC002,savings,Петров П.П.,2025-10-22,withdrawal,3690.28,Снятие наличных в банкомате - Сумма: 3690.28 руб.,68202.88
31,ACC002,savings,Петров П.П.,2025-12-18,withdrawal,3939.61,Покупка в магазине - Сумма: 3939.61 руб.,63938.88
34,ACC003,checking,Сидорова А.В.,2025-09-16,deposit,4643.33,Возврат средств - Сумма: 4643.33 руб.,35670.82
41,ACC003,checking,Сидорова А.В.,2025-11-23,withdrawal,4627.05,Оплата интернета - Сумма: 4627.05 руб.,64698.48

In [163]:
tx.loc[
    tx["owner"] == "Иванов И.И.",
    ["date", "operation_type", "amount", "balance_after"],
].head()

         date operation_type    amount  balance_after
0  2025-09-06        deposit  12891.65       64486.82
1  2025-09-15        deposit   3439.57      125056.31
2  2025-09-15        deposit  19010.45      138548.02
3  2025-09-28     withdrawal  13516.53       96631.56
4  2025-10-02        deposit  16055.06       80541.88

## Ваши вопросы

## 4. Сортировка данных

In [164]:
tx.sort_values(by="amount")

,account_id,account_type,owner,date,operation_type,amount,description,balance_after
29,ACC002,savings,Петров П.П.,2025-12-10,interest,93.21,Начисление процентов по вкладу - Сумма: 93.21 ...,16071.26
26,ACC002,savings,Петров П.П.,2025-11-26,interest,139.91,Начисление процентов по вкладу - Сумма: 139.91...,24124.56
20,ACC002,savings,Петров П.П.,2025-10-20,interest,148.15,Начисление процентов по вкладу - Сумма: 148.15...,25545.72
30,ACC002,savings,Петров П.П.,2025-12-15,interest,406.33,Начисление процентов по вкладу - Сумма: 406.33...,70062.24
25,ACC002,savings,Петров П.П.,2025-11-20,interest,416.94,Начисление процентов по вкладу - Сумма: 416.94...,71893.16
...,...,...,...,...,...,...,...,...
14,ACC001,checking,Иванов И.И.,2025-12-09,deposit,22906.01,Зачисление зарплаты - Сумма: 22906.01 руб.,119537.57
13,ACC001,checking,Иванов И.И.,2025-11-23,deposit,23154.87,Перевод с другого счета - Сумма: 23154.87 руб.,121616.74
5,ACC001,checking,Иванов И.И.,2025-10-06,deposit,23357.58,Перевод с другого счета - Сумма: 23357.58 руб.,161905.60
60,ACC004,savings,Козлов Д.М.,2025-12-04,deposit,23450.68,Перевод с другого счета - Сумма: 23450.68 руб.,66331.69
9,ACC001,checking,Иванов И.И.,2025-11-17,deposit,23575.29,Возврат средств - Сумма: 23575.29 руб.,44146.43

In [165]:
tx.sort_values(by="amount", ascending=False)

,account_id,account_type,owner,date,operation_type,amount,description,balance_after
9,ACC001,checking,Иванов И.И.,2025-11-17,deposit,23575.29,Возврат средств - Сумма: 23575.29 руб.,44146.43
60,ACC004,savings,Козлов Д.М.,2025-12-04,deposit,23450.68,Перевод с другого счета - Сумма: 23450.68 руб.,66331.69
5,ACC001,checking,Иванов И.И.,2025-10-06,deposit,23357.58,Перевод с другого счета - Сумма: 23357.58 руб.,161905.60
13,ACC001,checking,Иванов И.И.,2025-11-23,deposit,23154.87,Перевод с другого счета - Сумма: 23154.87 руб.,121616.74
14,ACC001,checking,Иванов И.И.,2025-12-09,deposit,22906.01,Зачисление зарплаты - Сумма: 22906.01 руб.,119537.57
...,...,...,...,...,...,...,...,...
25,ACC002,savings,Петров П.П.,2025-11-20,interest,416.94,Начисление процентов по вкладу - Сумма: 416.94...,71893.16
30,ACC002,savings,Петров П.П.,2025-12-15,interest,406.33,Начисление процентов по вкладу - Сумма: 406.33...,70062.24
20,ACC002,savings,Петров П.П.,2025-10-20,interest,148.15,Начисление процентов по вкладу - Сумма: 148.15...,25545.72
26,ACC002,savings,Петров П.П.,2025-11-26,interest,139.91,Начисление процентов по вкладу - Сумма: 139.91...,24124.56
29,ACC002,savings,Петров П.П.,2025-12-10,interest,93.21,Начисление процентов по вкладу - Сумма: 93.21 ...,16071.26

In [166]:
tx[["owner", "operation_type", "amount"]].sort_values(
    by=["owner", "amount"],
    ascending=[True, False],
).head(30)

          owner operation_type    amount
9   Иванов И.И.        deposit  23575.29
5   Иванов И.И.        deposit  23357.58
13  Иванов И.И.        deposit  23154.87
14  Иванов И.И.        deposit  22906.01
2   Иванов И.И.        deposit  19010.45
6   Иванов И.И.        deposit  17831.63
4   Иванов И.И.        deposit  16055.06
7   Иванов И.И.        deposit  15695.95
10  Иванов И.И.        deposit  15369.74
11  Иванов И.И.     withdrawal  14908.22
3   Иванов И.И.     withdrawal  13516.53
0   Иванов И.И.        deposit  12891.65
15  Иванов И.И.        deposit  10655.36
12  Иванов И.И.     withdrawal   8431.32
8   Иванов И.И.     withdrawal   7921.00
1   Иванов И.И.        deposit   3439.57
60  Козлов Д.М.        deposit  23450.68
56  Козлов Д.М.        deposit  22060.70
55  Козлов Д.М.        deposit  20855.20
58  Козлов Д.М.        deposit  19493.71
61  Козлов Д.М.        deposit  15687.15
48  Козлов Д.М.        deposit  15221.31
57  Козлов Д.М.        deposit  14794.28
54  Козлов Д.М.        deposit  13755.43
52  Козлов Д.М.     withdrawal  13184.94
59  Козлов Д.М.     withdrawal  12301.55
51  Козлов Д.М.     withdrawal  11596.33
49  Козлов Д.М.     withdrawal  10324.76
50  Козлов Д.М.        deposit   9316.67
64  Козлов Д.М.        deposit   5279.42

In [167]:
# Параметр inplace перезаписывает данные в DF
tx.sort_values(by=["owner", "amount"], ascending=[True, False], inplace=True)

In [168]:
tx.head(30)

,account_id,account_type,owner,date,operation_type,amount,description,balance_after
9,ACC001,checking,Иванов И.И.,2025-11-17,deposit,23575.29,Возврат средств - Сумма: 23575.29 руб.,44146.43
5,ACC001,checking,Иванов И.И.,2025-10-06,deposit,23357.58,Перевод с другого счета - Сумма: 23357.58 руб.,161905.60
13,ACC001,checking,Иванов И.И.,2025-11-23,deposit,23154.87,Перевод с другого счета - Сумма: 23154.87 руб.,121616.74
14,ACC001,checking,Иванов И.И.,2025-12-09,deposit,22906.01,Зачисление зарплаты - Сумма: 22906.01 руб.,119537.57
2,ACC001,checking,Иванов И.И.,2025-09-15,deposit,19010.45,Пополнение наличными - Сумма: 19010.45 руб.,138548.02
6,ACC001,checking,Иванов И.И.,2025-10-10,deposit,17831.63,Возврат средств - Сумма: 17831.63 руб.,179737.23
4,ACC001,checking,Иванов И.И.,2025-10-02,deposit,16055.06,Зачисление зарплаты - Сумма: 16055.06 руб.,80541.88
7,ACC001,checking,Иванов И.И.,2025-10-30,deposit,15695.95,Зачисление зарплаты - Сумма: 15695.95 руб.,106893.19
10,ACC001,checking,Иванов И.И.,2025-11-19,deposit,15369.74,Зачисление зарплаты - Сумма: 15369.74 руб.,51595.17
11,ACC001,checking,Иванов И.И.,2025-11-19,withdrawal,14908.22,Покупка в магазине - Сумма: 14908.22 руб.,110148.09
3,ACC001,checking,Иванов И.И.,2025-09-28,withdrawal,13516.53,Снятие наличных в банкомате - Сумма: 13516.53 ...,96631.56
0,ACC001,checking,Иванов И.И.,2025-09-06,deposit,12891.65,Зачисление зарплаты - Сумма: 12891.65 руб.,64486.82
15,ACC001,checking,Иванов И.И.,2025-12-30,deposit,10655.36,Перевод от клиента - Сумма: 10655.36 руб.,91197.24
12,ACC001,checking,Иванов И.И.,2025-11-20,withdrawal,8431.32,Снятие наличных в банкомате - Сумма: 8431.32 руб.,98461.87
8,ACC001,checking,Иванов И.И.,2025-11-08,withdrawal,7921.00,Оплата интернета - Сумма: 7921.0 руб.,36225.43
1,ACC001,checking,Иванов И.И.,2025-09-15,deposit,3439.57,Пополнение наличными - Сумма: 3439.57 руб.,125056.31
60,ACC004,savings,Козлов Д.М.,2025-12-04,deposit,23450.68,Перевод с другого счета - Сумма: 23450.68 руб.,66331.69
56,ACC004,savings,Козлов Д.М.,2025-10-22,deposit,22060.70,Перевод от клиента - Сумма: 22060.7 руб.,99998.25
55,ACC004,savings,Козлов Д.М.,2025-10-20,deposit,20855.20,Перевод с другого счета - Сумма: 20855.2 руб.,124430.41
58,ACC004,savings,Козлов Д.М.,2025-11-29,deposit,19493.71,Зачисление зарплаты - Сумма: 19493.71 руб.,143924.12
61,ACC004,savings,Козлов Д.М.,2025-12-11,deposit,15687.15,Перевод от клиента - Сумма: 15687.15 руб.,90633.56
48,ACC004,savings,Козлов Д.М.,2025-09-03,deposit,15221.31,Зачисление зарплаты - Сумма: 15221.31 руб.,105854.87
57,ACC004,savings,Козлов Д.М.,2025-10-26,deposit,14794.28,Зачисление зарплаты - Сумма: 14794.28 руб.,42881.01
54,ACC004,savings,Козлов Д.М.,2025-10-12,deposit,13755.43,Возврат средств - Сумма: 13755.43 руб.,80087.12
52,ACC004,savings,Козлов Д.М.,2025-09-20,withdrawal,13184.94,Снятие наличных в банкомате - Сумма: 13184.94 ...,74511.76
59,ACC004,savings,Козлов Д.М.,2025-11-30,withdrawal,12301.55,Снятие наличных в банкомате - Сумма: 12301.55 ...,87696.70
51,ACC004,savings,Козлов Д.М.,2025-09-14,withdrawal,11596.33,Покупка в магазине - Сумма: 11596.33 руб.,94258.54
49,ACC004,savings,Козлов Д.М.,2025-09-12,withdrawal,10324.76,Покупка в магазине - Сумма: 10324.76 руб.,75041.78
50,ACC004,savings,Козлов Д.М.,2025-09-12,deposit,9316.67,Перевод от клиента - Сумма: 9316.67 руб.,103575.21
64,ACC004,savings,Козлов Д.М.,2025-12-20,deposit,5279.42,Перевод с другого счета - Сумма: 5279.42 руб.,85366.54

In [ ]:
tx.nlargest(5, "amount")

## Ваши вопросы

## 5. Объединение таблиц

In [169]:
users = pd.read_csv("users_demo.csv")
ops = pd.read_csv("tx_demo.csv")
users

  user_id token_a
0     u1       AA
1      U2      BB
2     ​U3      CC
3      u4      DD

In [170]:
ops

  user_id   amount  token_b
0      U1    10.00       11
1      u2    20.00       22
2      U3  1337.42       33
3      U9     1.00       99

In [171]:
# Прямой merge по «грязным» ключам даёт мало совпадений
users.merge(ops, on="user_id")

Empty DataFrame
Columns: [user_id, token_a, amount, token_b]
Index: []

In [172]:
# Очистка ключа: пробелы, регистр, невидимые символы
def clean_id(s: pd.Series) -> pd.Series:
    return (
        s.astype(str)
         .str.replace("\u200b", "", regex=False)
         .str.strip()
         .str.upper()
    )

users = users.assign(uid=clean_id(users["user_id"]))
ops = ops.assign(uid=clean_id(ops["user_id"]))
merged = users.merge(ops, on="uid", suffixes=("_user", "_tx"))
merged

  user_id_user token_a uid user_id_tx   amount  token_b
0          u1       AA  U1         U1    10.00       11
1           U2      BB  U2         u2    20.00       22
2          ​U3      CC  U3         U3  1337.42       33

## Ваши вопросы

## 6. Группировка и преобразование данных

### Функции, выполняемые над данными датафрейма

In [173]:
df = pd.read_csv("AAPL.csv", sep=',', names=['date','open','high','low','close','adj_close','volume'], header=0)
df["date"] = pd.to_datetime(df["date"])
df.head()

        date      open      high       low     close  adj_close     volume
0 1980-12-12  0.513393  0.515625  0.513393  0.513393   0.406782  117258400
1 1980-12-15  0.488839  0.488839  0.486607  0.486607   0.385558   43971200
2 1980-12-16  0.453125  0.453125  0.450893  0.450893   0.357260   26432000
3 1980-12-17  0.462054  0.464286  0.462054  0.462054   0.366103   21610400
4 1980-12-18  0.475446  0.477679  0.475446  0.475446   0.376715   18362400

In [ ]:
def get_trend(row) -> str:
    return "bull" if row['open'] < row['close'] else 'bear' if row['open'] != row['close'] else 'floor'

df['trend'] = df.apply(get_trend, axis=1)

df.head()

In [ ]:
df['trend'] = df.apply(lambda row: "bull" if row['open'] < row['close'] else 'bear' if row['open'] != row['close'] else 'floor', axis=1)

df.head()

In [177]:
import numpy as np

df['trend'] = np.where(df['open'] < df['close'], 'bull',
           np.where(df['open'] != df['close'], 'bear', 'floor'))

df.head()

,date,open,high,low,close,adj_close,volume,weekday,month,trend
0,1980-12-12,0.513393,0.515625,0.513393,0.513393,0.406782,117258400,Friday,12,floor
1,1980-12-15,0.488839,0.488839,0.486607,0.486607,0.385558,43971200,Monday,12,bear
2,1980-12-16,0.453125,0.453125,0.450893,0.450893,0.357260,26432000,Tuesday,12,bear
3,1980-12-17,0.462054,0.464286,0.462054,0.462054,0.366103,21610400,Wednesday,12,floor
4,1980-12-18,0.475446,0.477679,0.475446,0.475446,0.376715,18362400,Thursday,12,floor

In [174]:
df['weekday'] = df['date'].dt.day_name()

df.tail()

,date,open,high,low,close,adj_close,volume,weekday
9904,2020-03-26,246.520004,258.679993,246.360001,258.440002,258.440002,63021800,Thursday
9905,2020-03-27,252.750000,255.869995,247.050003,247.740005,247.740005,51054200,Friday
9906,2020-03-30,250.740005,255.520004,249.399994,254.809998,254.809998,41994100,Monday
9907,2020-03-31,255.600006,262.489990,252.000000,254.289993,254.289993,49250500,Tuesday
9908,2020-04-01,246.500000,248.720001,239.130005,240.910004,240.910004,43956200,Wednesday

In [175]:
# Группировка по месяцам
df['month'] = df['date'].dt.month
monthly_stats = df.groupby('month').agg({
    'open': 'mean',
    'high': 'max',
    'low': 'min',
    'close': 'mean',
    'volume': 'sum'
}).round(2)

monthly_stats.head(20)

        open    high   low  close       volume
month
1      33.51  327.85  0.32  33.51  94794431400
2      34.51  327.22  0.33  34.58  67243825000
3      34.42  304.00  0.25  34.45  73637328400
4      29.90  248.72  0.26  29.89  72077343500
5      30.51  215.31  0.25  30.55  64978307300
6      30.06  201.57  0.23  30.03  65016931400
7      31.03  221.37  0.20  31.05  66568232300
8      32.59  228.87  0.22  32.62  64115150000
9      33.04  229.67  0.25  33.01  67401094800
10     34.13  249.75  0.27  34.14  85435284000
11     34.44  268.00  0.31  34.43  64637078000
12     33.15  293.97  0.32  33.14  64576133400

In [178]:
# Группировка по трендам
trend_analysis = df.groupby('trend').agg({
    'volume': ['count', 'mean', 'std'],
    'close': ['mean', 'std']
})

trend_analysis.head()

      volume                                  close
       count          mean           std       mean        std
trend
bear    4716  8.754739e+07  8.956486e+07  32.397675  57.251214
bull    4468  9.243870e+07  8.545972e+07  37.840409  62.551857
floor    725  3.391932e+07  2.930692e+07   1.867145  13.649035

### Pivot: длинный формат → широкая таблица

In [179]:
grid = pd.read_csv("grid_demo.csv")
grid

   row  col val
0    0    0   H
1    0    1   .
2    0    2   .
3    1    0   .
4    1    1   i
5    1    2   .
6    2    0   .
7    2    1   .
8    2    2   !

In [180]:
wide = grid.pivot(index="row", columns="col", values="val")
wide

col  0  1  2
row
0    H  .  .
1    .  i  .
2    .  .  !

In [ ]:
# Главная диагональ
"".join()

## Ваши вопросы

## 7. Экспорт данных

In [181]:
df.head()

,date,open,high,low,close,adj_close,volume,weekday,month,trend
0,1980-12-12,0.513393,0.515625,0.513393,0.513393,0.406782,117258400,Friday,12,floor
1,1980-12-15,0.488839,0.488839,0.486607,0.486607,0.385558,43971200,Monday,12,bear
2,1980-12-16,0.453125,0.453125,0.450893,0.450893,0.357260,26432000,Tuesday,12,bear
3,1980-12-17,0.462054,0.464286,0.462054,0.462054,0.366103,21610400,Wednesday,12,floor
4,1980-12-18,0.475446,0.477679,0.475446,0.475446,0.376715,18362400,Thursday,12,floor

In [ ]:
# Сохранение в CSV
df[['date', 'open', 'close']].to_csv('processed_stock_data.csv', index=False)

# Сохранение в Excel с несколькими листами
with pd.ExcelWriter('stock_analysis.xlsx') as writer:
    df.to_excel(writer, sheet_name='Raw Data', index=False)
    monthly_stats.to_excel(writer, sheet_name='Monthly Stats')
    trend_analysis.to_excel(writer, sheet_name='Trend Analysis')

# Сохранение в JSON
df.to_json('stock_data.json', orient='records', date_format='iso')

# Сохранение в Parquet
df.head(1000).to_parquet('aapl_sample.parquet', index=False)

## Ваши вопросы

## Итоги занятия

Научились работать с библиотекой Pandas:
- загружать данные из CSV, Excel, HTML, JSON, Parquet
- учитывать особенности чтения (`keep_default_na`, несколько листов Excel, `json_normalize`)
- фильтровать, сортировать, объединять (`merge`) и группировать данные
- работать с `pivot` и категориальными столбцами
- сохранять результат в CSV / Excel / JSON / Parquet

### Практика

Чтобы попрактиковаться в pandas:
1. Выгружаете себе докер образ

In [ ]:
docker pull ghcr.io/darynet/pandas-ctf:latest

2. Запускаете:

In [ ]:
docker run --rm -p 8888:8888 ghcr.io/darynet/pandas-ctf:latest


3. Открываете в браузере: http://127.0.0.1:8888
4. Брифинг: /ctf/notebooks/BRIEFING.ipynb  
Задание: /ctf/ASSIGNMENT.md
5. Пробуете собрать всех покемонов